amazonProperties:
  endpointUrl: https://s3.amazonaws.com
  accessKey: XXXXXXXXXX
  secretKey: XXXXXXXXXX
  bucketName: ft05-user-post
  elasticDomain: XXXXXXXXX
  apiGateway: XXXXXXXXX
  region: us-east-1



