amazonProperties:
  endpointUrl: https://s3-ap-southeast-1.amazonaws.com
  accessKey: AKIAIK6ICE3XZJH3QJXQ
  secretKey: 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
  bucketName: ft05
  userBucketName: ft05user
  region: ap-southeast-1



