amazonProperties:
  endpointUrl: s3-ap-southeast-1.amazonaws.com
  accessKey: AKIAJORUMIYAQMXEBVBA
  secretKey: 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
  bucketName: ft05-user-posts
  userBucketName: ft05user
  region: ap-southeast-1



